export const DELETE_SIGN_UP_DETAIL_KEY = "DELETE_SIGN_UP_DETAIL_KEY";
export const SET_SIGN_UP_DETAIL = "SET_SIGN_UP_DETAIL";
export const RESET_SIGN_UP_DETAIL = "RESET_SIGN_UP_DETAIL";
export const SET_MODULES_LIST = "SET_MODULES_LIST";
