export const navigations = {
  //routes
  CA_JOBS: "/ca-jobs",
  CAREER_ASCENT: "/career-ascents",
  COMPANY_PROFILE: "/company-profile",
  DASHBOARD: "/dashboard",
  FEEDBACK: "/feedback",
  FORGOT_PASSWORD: "/forgot-password",
  JOBS: "/jobs",
  LOGIN: "/login",
  NQCA: "/nqca-placements",
  OUT_SOURCED: "*",
  OVERSEES_CHAPTERS: "/overseas-chapters",
  PROFILE: "/profile",
  ROOT: "/",
  SIGN_UP: "/sign-up",
  TICKETS: "/tickets",
  VIEW_PROFILE: "/view-profile",
  WEB_VIEW: "/web-view",
  WOMEN_PARTTIME: "/women-placements",

  //sub routes
  APPLICATION_FORM: "application-form",
  JOB_APPLICANTS: "job-applicants",
  JOB_SEEKERS: "job-seekers",
  MODULE_LANDING_PAGE: "dashboard",
  POSTED_JOBS: "posted-jobs",
  ROUND_ONE: "round-one",
  ROUND_TWO: "round-two",
  SAVED_CANDIDATES: "saved-candidates",
};
