export const ADD_COUNTRY_DATA = "ADD_COUNTRY_DATA";
export const ADD_FUNCTIONAL_DATA = "ADD_FUNCTIONAL_DATA";
export const ADD_GENDER_PREFERENCE = "ADD_GENDER_PREFERENCE";
export const ADD_JOB_LOCATION = "ADD_JOB_LOCATION";
export const ADD_WORK_MODE = "ADD_WORK_MODE";
export const ADD_JOB_CATEGORY = "ADD_JOB_CATEGORY";
export const ADD_JOB_TYPE = "ADD_JOB_TYPE";
export const RESET_JOB_DATA = "RESET_JOB_DATA";
