export const writtenTestData = [
  {
    employer_name: "Google",
    interview_type: "Group Discussion",
    mode: "Virtual",
    interview_dates: "18/7/2023",
    shortlisting_round: "5",
    center_name: "AHEMDABAD-I",
    written_test: "Fail",
  },
  {
    employer_name: "Microsoft",
    interview_type: "Personal",
    mode: "Offline",
    interview_dates: "18/10/2023",
    shortlisting_round: "3",
    center_name: "AKOLA",
    written_test: "Fail",
  },
  {
    employer_name: "Phyllo",
    interview_type: "Personal",
    mode: "Virtual",
    interview_dates: "28/7/2023",
    shortlisting_round: "2",
    center_name: "AHEMDABAD-I",
    written_test: "FAIL",
  },
  {
    employer_name: "Daffodil",
    interview_type: "Personal",
    mode: "Offline",
    interview_dates: "18/1/2024",
    shortlisting_round: "4",
    center_name: "GURGAON",
    written_test: "Pass",
  },
];

export const campusInterviewData = [
  {
    employer_name: "Google",
    interview_type: "Group Discussion",
    mode: "Virtual",
    interview_dates_time: "18/7/2023",
    center_name: "AHEMDABAD-I",
    offer_provided: "Yes",
    offer_acceptance_deadline: "30/10/2023",
  },
  {
    employer_name: "Microsoft",
    interview_type: "Personal",
    mode: "Offline",
    interview_dates_time: "18/10/2023",
    center_name: "AKOLA",
    offer_provided: "No",
    offer_acceptance_deadline: "28/1/2024",
  },
  {
    employer_name: "Phyllo",
    interview_type: "Personal",
    mode: "Virtual",
    interview_dates_time: "28/7/2023",
    center_name: "AHEMDABAD-I",
    offer_provided: "No",
    offer_acceptance_deadline: "28/9/2023",
  },
  {
    employer_name: "Daffodil",
    interview_type: "Personal",
    mode: "Offline",
    interview_dates_time: "18/1/2024",
    center_name: "GURGAON",
    offer_provided: "Yes",
    offer_acceptance_deadline: "28/04/2024",
  },
];
