export const data = {
  meta: {
    total: 28,
    perPage: 10,
    currentPage: 1,
    lastPage: 3,
    from: 1,
    to: 10,
  },
  records: [
    {
      id: 198,
      application_id: "T0000198",
      name: "NQCA Placement",
      active_inactive: "Active",
      assigned_to: {
        id: null,
        name: null,
      },
      job_id: "2024-03-28T19:35:20.000000Z",
      designation: "nikhil",
      status: "Pending",
    },
    {
      id: 197,
      application_id: "T0000197",
      name: "Women Placement",
      active_inactive: "Inactive",
      assigned_to: {
        id: null,
        name: null,
      },
      job_id: "2024-03-28T19:35:07.000000Z",
      designation: "nikhil",
      status: "Pending",
    },
    {
      id: 196,
      application_id: "T0000196",
      name: "NQCA Placement",
      active_inactive: "Inactive",
      assigned_to: {
        id: null,
        name: null,
      },
      job_id: "2024-03-28T19:31:11.000000Z",
      designation: "nikhil",
      status: "Pending",
    },
    {
      id: 195,
      application_id: "T0000195",
      name: "NQCA Placement",
      active_inactive: "Inactive",
      assigned_to: {
        id: null,
        name: null,
      },
      job_id: "2024-03-28T19:30:42.000000Z",
      designation: "nikhil",
      status: "Pending",
    },
    {
      id: 194,
      application_id: "T0000193",
      name: "NQCA Placement",
      active_inactive: "Active",
      assigned_to: {
        id: null,
        name: null,
      },
      job_id: "2024-03-28T19:29:12.000000Z",
      designation: "nikhkdnfl",
      status: "Pending",
    },
    {
      id: 193,
      application_id: "T0000193",
      name: "NQCA Placement",
      active_inactive: "Inactive",
      assigned_to: {
        id: null,
        name: null,
      },
      job_id: "2024-03-28T19:28:29.000000Z",
      designation: "nikhil",
      status: "Pending",
    },
    {
      id: 192,
      application_id: "T0000192",
      name: "Career Ascent",
      active_inactive: "Active",
      assigned_to: {
        id: null,
        name: null,
      },
      job_id: "2024-03-28T19:27:10.000000Z",
      designation: "nikhil",
      status: "Pending",
    },
    {
      id: 191,
      application_id: "T0000191",
      name: "Overseas Placement",
      active_inactive: "Inactive",
      assigned_to: {
        id: null,
        name: null,
      },
      job_id: "2024-03-28T19:26:57.000000Z",
      designation: "nikhil",
      status: "Pending",
    },
    {
      id: 190,
      application_id: "T0000190",
      name: "Overseas Placement",
      active_inactive: "Inactive",
      assigned_to: {
        id: null,
        name: null,
      },
      job_id: "2024-03-28T19:25:25.000000Z",
      designation: "nikhil",
      status: "Pending",
    },
    {
      id: 189,
      application_id: "T0000189",
      name: "Overseas Placement",
      active_inactive: "Active",
      assigned_to: {
        id: null,
        name: null,
      },
      job_id: "2024-03-28T19:16:46.000000Z",
      designation: "nikhil",
      status: "Pending",
    },
  ],
};
