export const recordDataAhemdabad = [
  {
    employer_id: 1,
    employer_name: "Google",
    interview_type: "Group Discussion",
    mode: "Virtual",
    interview_dates: "18/7/2023, 4/9/23, 10/10/23",
    shortlisting_round: "4",
  },
  {
    employer_id: 2,
    employer_name: "Daffodil",
    interview_type: "Personal",
    mode: "Physical",
    interview_dates: "20/7/2023",
    shortlisting_round: "4",
  },
  {
    employer_id: 3,
    employer_name: "Unthinkable",
    interview_type: "Written",
    mode: "Physical",
    interview_dates: "22/7/2023",
    shortlisting_round: "3",
  },
  {
    employer_id: 4,
    employer_name: "Kelton Tech",
    interview_type: "Group Discussion",
    mode: "Physical",
    interview_dates: "30/10/2023",
    shortlisting_round: "2",
  },
  {
    employer_id: 5,
    employer_name: "Deloitte",
    interview_type: "Group Discussion",
    mode: "Physical",
    interview_dates: "11/11/2023",
    shortlisting_round: "2",
  },
  {
    employer_id: 4,
    employer_name: "Kelton Tech",
    interview_type: "Group Discussion",
    mode: "Physical",
    interview_dates: "30/10/2023",
    shortlisting_round: "2",
  },
];

export const recordDataAkola = [
  {
    employer_id: 1,
    employer_name: "Shriram Finance",
    interview_type: "Group Discussion",
    mode: "Virtual",
    interview_dates: "4/9/23",
    shortlisting_round: "4",
  },
  {
    employer_id: 2,
    employer_name: "Shooting Stars Studio",
    interview_type: "Personal",
    mode: "Physical",
    interview_dates: "20/7/2023,18/7/2023, 4/9/23, 10/10/23",
    shortlisting_round: "4",
  },
  {
    employer_id: 3,
    employer_name: "Muthoot Finance",
    interview_type: "Written",
    mode: "Physical",
    interview_dates: "22/12/2023",
    shortlisting_round: "3",
  },
  {
    employer_id: 4,
    employer_name: "TATA Motors",
    interview_type: "Group Discussion",
    mode: "Physical",
    interview_dates: "30/1/2024",
    shortlisting_round: "2",
  },
];

export const recordDataAurangabad = [
  {
    employer_id: 1,
    employer_name: "BALKRISHNA INDUSTRIES LIMITED.",
    interview_type: "Group Discussion",
    mode: "Physical",
    interview_dates: "10/10/23",
    shortlisting_round: "2",
  },
  {
    employer_id: 2,
    employer_name: "VARROC POLYMERS LIMITED",
    interview_type: "Personal",
    mode: "Physical",
    interview_dates: "20/2/2024",
    shortlisting_round: "4",
  },
  {
    employer_id: 3,
    employer_name: "FDC LIMITED",
    interview_type: "Written",
    mode: "Physical",
    interview_dates: "14/7/2023",
    shortlisting_round: "3",
  },
  {
    employer_id: 4,
    employer_name: "VARROC POLYMERS LIMITED",
    interview_type: "Group Discussion",
    mode: "Physical",
    interview_dates: "30/6/2023",
    shortlisting_round: "4",
  },
];

export const recordDataGurgaon = [
  {
    employer_id: 1,
    employer_name: "Hi Tech",
    interview_type: "Group Discussion",
    mode: "Virtual",
    interview_dates: "25/10/2023",
    shortlisting_round: "4",
  },
  {
    employer_id: 2,
    employer_name: "EXL",
    interview_type: "Personal",
    mode: "Physical",
    interview_dates: "20/3/2024, 24/3/2024",
    shortlisting_round: "4",
  },
  {
    employer_id: 3,
    employer_name: "Locuz",
    interview_type: "Written",
    mode: "Physical",
    interview_dates: "22/2/2024",
    shortlisting_round: "2",
  },
  {
    employer_id: 4,
    employer_name: "Impac",
    interview_type: "Group Discussion",
    mode: "Virtual",
    interview_dates: "30/1/2024",
    shortlisting_round: "3",
  },
];
