export const MODULE_LIST = "MODULE_LIST";
export const SET_GLOBAL_SESSION_LIST = "SET_GLOBAL_SESSION_LIST";
export const SELECTED_SESSION = "SELECTED_SESSION";
export const SET_IS_GETTING_GLOBAL_SESSION_LIST =
  "SET_IS_GETTING_GLOBAL_SESSION_LIST";
export const SET_ROUNDS_DATA = "SET_ROUNDS_DATA";
