export const mapApiDataToUI = () => {
  return {
    monthly: [
      {
        key: "basic",
        label: "label.basic",
        value: "",
        placeholder: "label.basic",
        isMandatory: true,
        isRow: true,
        maxLength: 9,
        isRupee: true,
        isNumeric: true,
      },
      {
        key: "hra",
        label: "label.hra",
        value: "",
        isMandatory: true,
        placeholder: "label.hra",
        isRow: true,
        maxLength: 9,
        isRupee: true,
        isNumeric: true,
      },
      {
        key: "others",
        label: "label.others",
        value: "",
        isMandatory: true,
        placeholder: "label.others",
        isRow: true,
        maxLength: 9,
        isRupee: true,
        isNumeric: true,
      },
      {
        key: "fixedPay",
        label: "label.fixedPay",
        value: "",
        isMandatory: true,
        placeholder: "label.fixedPay",
        isRow: true,
        maxLength: 9,
        isRupee: true,
        isNumeric: true,
      },
      {
        key: "variablePay",
        label: "label.variablePay",
        value: "",
        isMandatory: true,
        placeholder: "label.variablePay",
        isRow: true,
        maxLength: 9,
        isRupee: true,
        isNumeric: true,
      },
      {
        key: "semiVariable",
        label: "label.semiVariable",
        value: "",
        isMandatory: true,
        placeholder: "label.semiVariable",
        isRow: true,
        maxLength: 9,
        isRupee: true,
        isNumeric: true,
      },
      {
        key: "takeHome",
        label: "label.takeHome",
        value: "",
        isMandatory: true,
        placeholder: "label.takeHome",
        isRow: true,
        maxLength: 9,
        isRupee: true,
        isNumeric: true,
      },
      {
        key: "grossSalary",
        label: "label.gross_Salary",
        value: "",
        isMandatory: true,
        placeholder: "label.enter_gross_Salary",
        isRow: true,
        maxLength: 9,
        isRupee: true,
        isEditable: false,
        isNumeric: true,
      },
    ],
    yearly: [
      {
        key: "oneTimePayment",
        label: "label.oneTimePayment",
        value: "",
        isMandatory: true,
        placeholder: "label.oneTimePayment",
        isRow: true,
        maxLength: 9,
        isRupee: true,
        isNumeric: true,
      },
      {
        key: "totalGrossSalary",
        label: "label.totalGrossSalary",
        value: "",
        isMandatory: true,
        placeholder: "label.totalGrossSalary",
        isRow: true,
        isEditable: false,
        maxLength: 9,
        isRupee: true,
        isNumeric: true,
      },
      {
        key: "ctc",
        label: "label.ctc",
        value: "",
        isMandatory: true,
        isEditable: false,
        placeholder: "label.ctc",
        maxLength: 9,
        isRupee: true,
        isNumeric: true,
      },
    ],
    Posting_Place: [
      {
        key: "others",
        label: "label.others",
        value: "",
      },
      {
        key: "obc",
        label: "label.OBC",
        value: "",
      },
      {
        key: "sc",
        label: "label.SC",
        value: "",
      },
      {
        key: "st",
        label: "label.ST",
        value: "",
      },
      {
        key: "ph",
        label: "label.PH",
        value: "",
      },
      {
        key: "general",
        label: "label.general",
        value: "",
      },
    ],
  };
};
