export const mapApiDataToUI = () => {
  return {
    Monthly: [
      {
        key: "basic",
        label: "label.basic",
        value: "",
        placeholder: "label.basic",
        isRow: true,
        maxLength: 9,
        isRupee: true,
        isNumeric: true,
      },
      {
        key: "hra",
        label: "label.hra",
        value: "",
        placeholder: "label.hra",
        isRow: true,
        maxLength: 9,
        isRupee: true,
        isNumeric: true,
      },
      {
        key: "others",
        label: "label.others",
        value: "",
        placeholder: "label.others",
        isRow: true,
        maxLength: 9,
        isRupee: true,
        isNumeric: true,
      },
      {
        key: "grossSalary",
        label: "label.grossSalary",
        value: "",
        placeholder: "label.grossSalary",
        isRow: true,
        maxLength: 9,
        isRupee: true,
        isNumeric: true,
      },
      {
        key: "fixedPay",
        label: "label.fixedPay",
        value: "",
        placeholder: "label.fixedPay",
        isRow: true,
        maxLength: 9,
        isRupee: true,
        isNumeric: true,
      },
      {
        key: "variablePay",
        label: "label.variablePay",
        value: "",
        placeholder: "label.variablePay",
        isRow: true,
        maxLength: 9,
        isRupee: true,
        isNumeric: true,
      },
      {
        key: "semiVariable",
        label: "label.semiVariable",
        value: "",
        placeholder: "label.semiVariable",
        isRow: true,
        maxLength: 9,
        isRupee: true,
        isNumeric: true,
      },
      {
        key: "takeHome",
        label: "label.takeHome",
        value: "",
        placeholder: "label.takeHome",
        isRow: true,
        maxLength: 9,
        isRupee: true,
        isNumeric: true,
      },
    ],
    Yearly: [
      {
        key: "totalGrossSalary",
        label: "label.totalGrossSalary",
        value: "",
        placeholder: "label.totalGrossSalary",
        isRow: true,
        maxLength: 9,
        isRupee: true,
        isNumeric: true,
      },
      {
        key: "oneTimePayment",
        label: "label.oneTimePayment",
        value: "",
        placeholder: "label.oneTimePayment",
        isRow: true,
        maxLength: 9,
        isRupee: true,
        isNumeric: true,
      },
      {
        key: "ctc",
        label: "label.ctc",
        value: "",
        placeholder: "label.ctc",
        maxLength: 9,
        isRupee: true,
        isNumeric: true,
      },
    ],
  };
};
